### ISSUE TITLE
Task exec:task not found

### ISSUE THREAD

**Issue by gizburdt** [jharding/grunt-exec#43]
Hi,

This is my code:
```
exec: {
        wp_download: {
            cmd: 'wp core download --locale=<%= wp.download.locale %>  --version=<%= wp.download.version %>'
        }
},
```

But when I try to run my task, it says Warning: Task "exec:wp_download" not found.

Hope you can help :)

**Comment by manigandaprabu** [comment]
thank you gizburdt

**Comment by VinSpee** [comment]
Sorry to bump, but I'm having this same issue.

```
module.exports = {
  webpack: {
    prod: {
      cmd: 'npm run js:build'
    },
    dev: {
      cmd: 'echo hello'
    }
  },
};
```

running

`grunt exec:webpack:dev`

results in
```

Running "exec:webpack:dev" (exec) task
>> Missing command property.
Warning: Task "exec:webpack:dev" failed. Use --force to continue.
```

any ideas?

**Comment by jlf123** [comment]
bump...having same issue ^^^

`exec: {
    git_tag: {
        command: '<%= gitinfo.tag %>
    }
}`

**Comment by gwicksted** [comment]
Re-opening issue

**Comment by gwicksted** [comment]
@VinSpee I don't think you can have `exec:webpack:dev` because that's two inner-layers of names.  If you have `exec:webpackdev` it should work.  This is the case with all grunt plugins -- I think ?

@jlf123 your command should work if you have a terminating half quote.  Replacing the grunt.template string with 'echo hello world' works but I'll do some testing specifically with grunt.template strings

**Comment by gwicksted** [comment]
I have confirmed the following works (displays "world") -- please provide a full gruntfile example if you're still getting that error:

```javascript
module.exports = function(grunt) {

  grunt.initConfig({
    hello: "world",
    exec: {
      git_tag: { command: 'echo <%= hello %>' }
    }
  });
  
  grunt.loadTasks("tasks");
}
```

**Comment by jlf123** [comment]
You're right, that was my bad. thanks!
