### ISSUE TITLE
exit code 9 when use this cmd: zip -r example.zip [many files or directories]

### ISSUE THREAD

**Issue by yibuyisheng** [jharding/grunt-exec#55]
the child process exits with code 9 when I use the command zip to zip many files and directories, but it's ok to directly use the same command to zip these files and directories.

**Comment by tjbaker** [comment]
I hit this today, can't zip many files.

**Comment by tjbaker** [comment]
If I run zip with --quiet it works, seems as though stdout is overflowing something.

**Comment by eabovsky** [comment]
I also experienced... @tjbaker - thanks for the tip, that also worked for me as a work-around. I'm on OSX 10.10.

**Comment by gwicksted** [comment]
This is expected behavior from `child_process.exec` due to the default options provided.  The default buffer size is `200*1024` for `stdout` and `stderr` and if the process exceeds that, it is killed.

Unfortunately this is absent from the grunt-exec documentation; however, that is about to change.  I'm in the process of documenting the options available, their defaults, and expected outcomes (such as this one) from the Node documentation.
