### ISSUE TITLE
Piping to "xargs kill" makes Grunt fail

### ISSUE THREAD

**Issue by heliodor** [jharding/grunt-exec#60]
**Successful run**
Config:
```
dist_dev_ks: {
    command: [
        [
            'ps -ef',
            'grep python',
            'grep runserver',
            'grep 9474',
            "awk '{print $2}'",
        ].join(' | '),
    ].join(' && '),
},
```

Execution:
```
$ grunt exec:dist_dev_ks
Running "exec:dist_dev_ks" (exec) task
94833
94836
94897

Done, without errors.
```

**Failed run after adding the piping to xargs kill**
Config:
```
dist_dev_ks: {
    command: [
        [
            'ps -ef',
            'grep python',
            'grep runserver',
            'grep 9474',
            "awk '{print $2}'",
            'xargs kill',
        ].join(' | '),
    ].join(' && '),
},
```

Execution:
```
$ grunt exec:dist_dev_ks
Running "exec:dist_dev_ks" (exec) task
>> Exited with code: 0.
Warning: Task "exec:dist_dev_ks" failed. Use --force to continue.

Aborted due to warnings.
```

If I use --verbose:
```
Expecting exit code 0
>> Exited with code: 0.
Warning: Task "exec:dist_dev_ks" failed. Use --force to continue.
```

**Comment by gwicksted** [comment]
Will investigate further

**Comment by gwicksted** [comment]
Thrown errors are now output by default (when no callback provided).  The thrown error would at least give a hint at what the cause of the exit was.

**Comment by heliodor** [comment]
@gwicksted, turns out the problem is that when you run `ps aux | grep "..."`, the `grep` command will show up in the results alongside the command searched for. The `kill` command will fail with something like `kill: 92342: No such process`.

`grunt-exec` version 1.0.1 does not show the error (even when `grunt` is run with `-vvvvv`):

```
Running "exec:dist_dev_ks" (exec) task
Verifying property exec.dist_dev_ks exists in config...OK
File: [no files]
Max stdout+stderr size is 204800 bytes

ps aux | grep python | grep runserver | grep 8002 | awk '{print $2}' | xargs kill
Expecting exit code 0
>> Exited with code: 0.
>> Error executing child process: Error: Command failed: ps aux | grep python | grep runserver | grep 8002 | awk '{print $2}' | xargs kill
Warning: Task "exec:dist_dev_ks" failed. Use --force to continue.

Aborted due to warnings.
```

**Comment by gwicksted** [comment]
@heliodor thank you for re-testing this! I'm sure we've all hit that before with `ps aux | grep ...`

A simple trick is placing the grep regex in quotes and including a character group around the first character eg. `ps aux | grep "[p]ython` will cause grep to match "python" but not "grep [p]ython" since p is followed by the literal `]`.  See [http://unix.stackexchange.com/questions/74185/how-can-i-prevent-grep-from-showing-up-in-ps-results](stack exchange) for alternative solutions.

Unfortunately, that error is all we get back from node regarding the error.  If you set `stdout` and/or `stderr` to `true` in the grunt-exec `options`, it may show kill's output as well which I'm sure would be beneficial.
